name: nmap
command: nmap
output: text
args:
  default: ["-oN", "-"]
  flags:
    fast: ["-F"]
    intense: ["-T4", "-A", "-v"]
    stealth: ["-sS", "-sV", "-T2"]
    fingerprint: ["-T4", "-v", "-sV", "-sC", "--open"]
    service_scan: ["-sV", "-sC", "-T4"]
    comprehensive: ["-T4", "-A", "-sV", "-sC", "--script=default,discovery"]
    target_only: ["-T4", "-sV", "--open"]
execution:
  timeout_seconds: 600  # 10 minutes for nmap scans
  max_memory_mb: 256
  allowed: true
  security:
    max_arg_length: 1000
    forbidden_patterns: [";", "|", "&", "`", "$(", "rm", "del"]
mappings:
  - type: host
    query: "nmaprun.host"
    fields:
      address: "address.@addr"
      hostname: "hostnames.hostname.@name"
      status: "status.@state"