name: subfinder
command: subfinder
output: json
args:
  default: ["-silent", "-o", "-", "-json"]
  flags:
    passive_only: ["-passive", "-silent", "-json"]
    all_sources: ["-all", "-silent", "-json"]
    timeout_short: ["-timeout", "5", "-silent", "-json"]
    timeout_long: ["-timeout", "30", "-silent", "-json"]
    recursive: ["-recursive", "-silent", "-json"]
    verbose: ["-v", "-json"]
    ct_only: ["-sources", "crtsh,censys", "-silent", "-json"]
    fast_scan: ["-passive", "-timeout", "10", "-silent", "-json"]
    comprehensive: ["-all", "-recursive", "-timeout", "60", "-silent", "-json"]
execution:
  timeout_seconds: 120  # 2 minutes for passive enumeration
  max_memory_mb: 128
  allowed: true
  security:
    max_arg_length: 500
    forbidden_patterns: [";", "|", "&", "`", "$(", "rm", "del"]
mappings:
  - type: subdomain
    query: "[]"
    fields:
      host: "host"
      ip: "ip"
      source: "source"