version: "0.1.1"

# Which scan template to use by default and will not require flag
default_template: basic

# Available scan templates  
templates:
  - basic

# Parallel execution configuration
concurrency:
  max_concurrent_workflows: 4
  enable_auto_limit: true
  use_errgroup: true
