name: nslookup
command: nslookup
output: text
args:
  default: []
  flags:
    debug: ["-debug"]
    verbose: ["-v"]
    recursive: ["-recurse"]
    authoritative: ["-type=SOA"]
    mx_lookup: ["-type=MX"]
    ns_lookup: ["-type=NS"]
    txt_lookup: ["-type=TXT"]
    a_lookup: ["-type=A"]
    aaaa_lookup: ["-type=AAAA"]
    ptr_lookup: ["-type=PTR"]
execution:
  timeout_seconds: 30  # 30 seconds for DNS lookups
  max_memory_mb: 64
  allowed: true
  security:
    max_arg_length: 200
    forbidden_patterns: [";", "|", "&", "`", "$(", "rm", "del"]
mappings:
  - type: dns_record
    query: "*"
    fields:
      record_type: "type"
      value: "value"
      name: "name"