name: naabu
command: naabu
output: json
args:
  default: ["-json", "-silent"]
  flags:
    fast: ["-p", "80,443,8080,8443", "-host"]
    common: ["-p", "80,443", "-host"]
    top100: ["-p", "1-100", "-host"]
    top1000: ["-p", "1-1000", "-host"]
    full: ["-p-", "-host"]
    basic: ["-p", "21,22,23,25,53,80,110,111,135,139,143,443,993,995,1723,3306,3389,5900,8080", "-host"]
mappings:
  - type: port
    query: "[]"
    fields:
      ip: "ip"
      port: "port"
      protocol: "proto"