name: dig
command: dig
output: text
args:
  default: ["+short"]
  flags:
    short: ["+short"]
    trace: ["+trace"]
    verbose: ["+verbose"]
    detailed: ["+answer", "+authority", "+additional"]
    reverse: ["-x"]
    any: ["ANY"]
    tcp: ["+tcp"]
    dnssec: ["+dnssec", "+multi"]
execution:
  timeout_seconds: 30  # 30 seconds for DNS lookups
  max_memory_mb: 64
  allowed: true
  security:
    max_arg_length: 200
    forbidden_patterns: [";", "|", "&", "`", "$(", "rm", "del"]
mappings: []