# IPCrawler Security Validation Rules
# Analyzes and validates YAML files in tools/ and workflows/ for malicious code
# IMPORTANT: This file provides validation rules only - it does NOT control execution

security_validation:
  # YAML injection prevention
  yaml_security:
    # Forbidden YAML constructs that could lead to code injection
    forbidden_yaml_tags:
      - "!!python/object"          # Python object deserialization
      - "!!python/object/apply"    # Python function execution
      - "!!python/object/new"      # Python object instantiation
      - "!!js/function"            # JavaScript function execution
      - "!!ruby/object"            # Ruby object deserialization
      - "!!java"                   # Java object deserialization
      - "!!binary"                 # Binary data execution
      - "!!omap"                   # Ordered map potential exploits
      - "!!pairs"                  # Pairs potential exploits
      - "!!set"                    # Set potential exploits
    
    # Dangerous YAML patterns
    forbidden_yaml_patterns:
      - "eval("                    # Code evaluation
      - "exec("                    # Code execution  
      - "__import__"               # Python imports
      - "subprocess"               # Subprocess execution
      - "os.system"                # OS command execution
      - "shell=True"               # Shell execution
      - "`.*`"                     # Backtick command execution
      - "\\$\\((?!.*\\}\\})"       # Command substitution (but not {{}} templates)
      - "\\$\\{(?!.*\\}\\})"       # Variable substitution (but not {{}} templates)
      - "#!/"                      # Shebang lines
      - "file://"                  # File protocol access
      - "http://"                  # Unencrypted HTTP (require HTTPS)
      - "ftp://"                   # FTP protocol access
      
  # Tool configuration validation
  tool_config_validation:
    # Required fields in tool configs
    required_fields:
      - "name"                     # Tool name must be present
      - "command"                  # Command must be present
      - "execution"                # Execution config must be present
      - "execution.allowed"        # Must explicitly allow/disallow
      
    # Validation rules for tool commands
    command_validation:
      # Only allow specific approved commands
      allowed_commands:
        - "nmap"
        - "naabu" 
        - "dig"
        - "nslookup"
        - "subfinder"
        - "amass"
        - "gobuster"
        - "ffuf"
        - "masscan"
        - "zmap"
        - "host"
        - "curl"
        - "wget"
        
      # Forbidden command patterns (exact matches or word boundaries)
      forbidden_command_patterns:
        - "\\brm\\b"               # File deletion (word boundary)
        - "\\bdel\\b"              # File deletion (word boundary)
        - "\\bformat\\b"           # Disk formatting (word boundary)
        - "\\bmkfs\\b"             # Filesystem creation (word boundary)
        - "\\bdd\\b"               # Direct disk access (word boundary)
        - "\\bsudo\\b"             # Privilege escalation (word boundary)
        - "\\bsu\\b"               # User switching (word boundary, not "subfinder")
        - "chmod"                  # Permission changes
        - "chown"                  # Ownership changes
        - "passwd"                 # Password changes
        - "useradd"                # User creation
        - "usermod"                # User modification
        - "nc"                     # Netcat (reverse shells)
        - "bash"                   # Shell access
        - "sh"                     # Shell access
        - "python"                 # Script execution
        - "perl"                   # Script execution
        - "php"                    # Script execution
        - "node"                   # Script execution
        
    # Argument validation rules
    argument_validation:
      # Maximum lengths to prevent buffer overflows
      max_lengths:
        tool_name: 50
        command: 100
        single_argument: 1000
        total_arguments: 5000
        
      # Forbidden argument patterns
      forbidden_argument_patterns:
        - ";"                      # Command chaining
        - "\\s\\|\\s"              # Shell piping (space-pipe-space)
        - "\\s&\\s"               # Background execution (space-&-space)
        - "\\s&&\\s"              # Conditional execution (space-&&-space)
        - "\\s\\|\\|\\s"          # Alternative execution (space-||-space)
        - "`"                      # Command substitution
        - "$("                     # Command substitution
        - ">/"                     # Redirect to filesystem root
        - "/dev/"                  # Device access
        - "/proc/"                 # Process filesystem
        - "/sys/"                  # System filesystem
        - "../"                    # Directory traversal
        - "..\\"                   # Directory traversal (Windows)
        
    # File path validation
    path_validation:
      # Only allow output to designated directories
      allowed_output_dirs:
        - "out/"
        - "reports/"
        - "temp/"
        - "/tmp/"
        
      # Forbidden path patterns
      forbidden_paths:
        - "/etc/"                  # System configuration
        - "/bin/"                  # System binaries
        - "/sbin/"                 # System binaries
        - "/usr/bin/"             # User binaries
        - "/var/"                  # Variable data
        - "/root/"                # Root directory
        - "/home/"                # User directories (except output)
        - "C:\\"                  # Windows system drive
        - "Program Files"          # Windows programs
        - "System32"               # Windows system
        
  # Workflow configuration validation
  workflow_config_validation:
    # Required fields in workflow configs
    required_fields:
      - "id"                       # Workflow ID must be present
      - "description"              # Description must be present
      - "steps"                    # Steps must be present
      - "execution"                # Execution config must be present
      
    # Step validation rules
    step_validation:
      # Maximum limits to prevent resource exhaustion
      max_limits:
        steps_per_workflow: 20
        dependencies_per_step: 5
        override_args_per_step: 10
        
      # Required step fields
      required_step_fields:
        - "id"                     # Step ID required
        
      # Valid step types
      allowed_step_types:
        - "tool_execution"         # Tool execution step
        - "merge_files"            # File merging
        - "json_to_hostlist"      # Data transformation
        - "data_transformation"    # Data processing
        
      # Tool validation for steps
      allowed_tools_in_steps:
        - "nmap"
        - "naabu"
        - "dig"
        - "nslookup" 
        - "subfinder"
        - "amass"
        - "gobuster"
        - "ffuf"
        
  # General security rules
  general_security:
    # File size limits to prevent DoS
    max_file_sizes:
      tool_config: "10KB"
      workflow_config: "50KB"
      
    # Encoding validation
    required_encoding: "UTF-8"
    
    # Content validation
    max_line_length: 5000        # Allow longer lines for port lists
    max_lines_per_file: 500
    
    # Nested structure limits
    max_yaml_depth: 10
    max_array_length: 100
    max_object_keys: 50
    
  # Validation error messages
  error_messages:
    forbidden_yaml_tag: "Forbidden YAML tag detected: {tag}"
    forbidden_yaml_pattern: "Forbidden YAML pattern detected: {pattern}"
    forbidden_command: "Forbidden command detected: {command}"
    forbidden_argument: "Forbidden argument pattern detected: {pattern}"
    forbidden_path: "Forbidden path detected: {path}"
    missing_required_field: "Required field missing: {field}"
    invalid_step_type: "Invalid step type: {type}"
    file_too_large: "File too large: {size} > {max_size}"
    line_too_long: "Line too long: {length} > {max_length}"
    too_many_lines: "Too many lines: {count} > {max_count}"
    yaml_depth_exceeded: "YAML nesting too deep: {depth} > {max_depth}"
    invalid_encoding: "Invalid file encoding: expected UTF-8"
    
# Validation severity levels
severity_levels:
  critical:        # Blocks execution completely
    - "forbidden_yaml_tag"
    - "forbidden_command"
    - "code_injection"
    
  high:           # Blocks execution with warning
    - "forbidden_yaml_pattern"
    - "forbidden_argument"
    - "forbidden_path"
    
  medium:         # Allows execution with warning
    - "missing_optional_field"
    - "deprecated_feature"
    
  low:            # Informational only
    - "style_violation"
    - "recommendation"