# IPCrawler API Configuration
api:
  # API Keys (set via environment variables for security)
  keys:
    shodan: "${SHODAN_API_KEY}"
    censys: "${CENSYS_API_KEY}"
    virustotal: "${VIRUSTOTAL_API_KEY}"
    securitytrails: "${SECURITYTRAILS_API_KEY}"
    hunter_io: "${HUNTER_IO_API_KEY}"
    
  # API Endpoints
  endpoints:
    shodan: "https://api.shodan.io"
    censys: "https://search.censys.io/api"
    virustotal: "https://www.virustotal.com/api/v3"
    securitytrails: "https://api.securitytrails.com/v1"
    hunter_io: "https://api.hunter.io/v2"
    
  # Rate Limiting
  rate_limits:
    requests_per_minute: 60  # Max requests per minute
    burst_size: 10           # Burst size for rate limiting
    backoff_seconds: 60      # Backoff time when rate limited