# IPCrawler Network Configuration
network:
  proxy:
    enabled: false           # Enable proxy support
    http: ""                 # HTTP proxy (http://proxy:port)
    https: ""                # HTTPS proxy (https://proxy:port)
    socks5: ""               # SOCKS5 proxy (socks5://proxy:port)
    no_proxy:                # Bypass proxy for these hosts
      - "localhost"
      - "127.0.0.1"
      - "*.local"
      
  dns:
    servers:                 # DNS servers to use
      - "8.8.8.8"           # Google DNS
      - "1.1.1.1"           # Cloudflare DNS
      - "9.9.9.9"           # Quad9 DNS
    timeout: 5               # DNS resolution timeout (seconds)
    retries: 3               # Number of DNS retry attempts
    
  interfaces:
    prefer_ipv4: true        # Prefer IPv4 over IPv6
    interface: ""            # Specific network interface to use (eth0, wlan0, etc.)