# IPCrawler Output Configuration
# Enable timestamp in log output
timestamp: true
time_format: "RFC3339Nano"

# info output
info:
  directory: "./output/logs/info/"
  level: "info"

# error output
error:
  directory: "./output/logs/error/"
  level: "error"

# warning output
warning:
  directory: "./output/logs/warning/"
  level: "warning"

# debug output
debug:
  directory: "./output/logs/debug/"
  level: "debug"

# raw output
raw:
  directory: "./output/raw/"