# IPCrawler Output Configuration
# Output will be organized under workspace/{{target}}/ directory structure
# Each target gets its own workspace with subdirectories for different output types

output:
  # Base workspace directory (no hardcoded paths)
  workspace_base: "./workspace"

  # Enable timestamp in log output
  timestamp: true
  time_format: "RFC3339Nano"

  # info output
  info:
    directory: "{{workspace}}/logs/info/"
    level: "info"

  # error output
  error:
    directory: "{{workspace}}/logs/error/"
    level: "error"

  # warning output
  warning:
    directory: "{{workspace}}/logs/warning/"
    level: "warning"

  # debug output
  debug:
    directory: "{{workspace}}/logs/debug/"
    level: "debug"

  # raw tool output
  raw:
    directory: "{{workspace}}/raw/"

  # scan results (not currently in config struct but available for tools)
  scans:
    directory: "{{workspace}}/scans/"

  # reports and summaries (not currently in config struct but available for tools)
  reports:
    directory: "{{workspace}}/reports/"