# IPCrawler Security Configuration
security:
  os_detection: true
  execution:
    tools_root: "./tools/bin"        # all executables must resolve under this dir
    args_validation: true          # validate scripts before execution
    exec_validation: true          # validate executables before execution
