# IPCrawler TUI Configuration
# Zero hardcoded dimensions - all layout values configured here

# Layout Configuration
layout:
  # Responsive breakpoints for different terminal sizes
  breakpoints:
    large: 120    # Three-panel layout: [Nav] | [Main] | [Status]
    medium: 80    # Two-panel layout: [Nav] | [Main+Status]
    small: 40     # Minimum usable width for single-panel layout
  
  # Consistent spacing values (no magic numbers)
  spacing:
    none: 0
    small: 1
    medium: 2
    large: 4
  
  # Panel sizing ratios (calculated dynamically)
  panels:
    navigation:
      min_width: 20
      preferred_width_ratio: 0.25   # 25% of available width in large layout
    main:
      min_width: 40  
      preferred_width_ratio: 0.50   # 50% of available width in large layout
    status:
      min_width: 15
      preferred_width_ratio: 0.25   # 25% of available width in large layout
  
  # Border and padding configuration
  borders:
    style: "rounded"              # rounded, normal, thick, double
    color: "#444444"              # Border color (monochrome gray)
    width: 2                      # Border width in characters
  
  # Header and footer dimensions
  header:
    height: 3                     # Title + status + spacing
    show_when_height_above: 15    # Only show header if terminal > 15 lines
  
  footer:
    height: 2                     # Status + spacing
    show_help_shortcut: true      # Show help shortcut in footer

# Theme Configuration  
theme:
  mode: "monochrome"              # monochrome | adaptive | color
  high_contrast: true             # Accessibility-focused high contrast
  
  # Accessibility features
  accessibility:
    color_disabled_fallback: true     # Support terminals without color
    screen_reader_compatible: true    # Structured output for assistive tech
    minimum_contrast_ratio: 7.0       # WCAG AAA compliance
  
  # Monochrome color palette (high contrast)
  colors:
    primary: "#ffffff"            # White text
    secondary: "#cccccc"          # Light gray
    accent: "#888888"             # Medium gray  
    background: "#000000"         # Black background
    border: "#444444"             # Dark gray borders
    muted: "#666666"              # Muted gray for less important text
    
    # Status colors (monochrome variants)
    success: "#ffffff"            # White for completed
    warning: "#cccccc"            # Light gray for warnings
    error: "#ffffff"              # White for high visibility errors
    info: "#888888"               # Medium gray for info

# Status Symbols and Icons
symbols:
  # Workflow and tool status indicators
  status:
    running: "●"                  # Solid circle for active
    completed: "✓"                # Checkmark for success
    failed: "✗"                   # X mark for failure
    pending: "○"                  # Hollow circle for waiting
    paused: "⏸"                   # Pause symbol
    cancelled: "⏹"                # Stop symbol
  
  # Progress and loading indicators  
  progress:
    spinner: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
    filled: "█"                   # Progress bar filled segment
    empty: " "                    # Progress bar empty segment
    
  # Navigation and focus indicators
  navigation:
    cursor: ">"                   # Current selection indicator
    focus_border: "heavy"         # Border style for focused panels
    
  # Special characters
  special:
    bullet: "•"                   # List bullet points
    arrow_right: "→"              # Right arrow
    arrow_left: "←"               # Left arrow
    ellipsis: "..."               # Text truncation indicator

# Keyboard Shortcuts and Interaction
keymap:
  # Global shortcuts (available everywhere)
  global:
    quit: ["q", "ctrl+c"]         # Exit application
    help: ["?"]                   # Toggle help panel
    refresh: ["ctrl+r"]           # Refresh data
    debug: ["ctrl+d"]             # Toggle debug mode
  
  # Navigation shortcuts
  navigation:
    up: ["up", "k"]               # Move up in lists/tables
    down: ["down", "j"]           # Move down in lists/tables
    left: ["left", "h"]           # Move left or previous
    right: ["right", "l"]         # Move right or next
    next_panel: ["tab"]           # Focus next panel
    prev_panel: ["shift+tab"]     # Focus previous panel
    
    # Direct panel focus (large layout)
    focus_nav: ["1"]              # Focus navigation panel
    focus_main: ["2"]             # Focus main panel  
    focus_status: ["3"]           # Focus status panel
    
    # Small layout view switching
    next_view: ["space"]          # Switch to next view
    prev_view: ["shift+space"]    # Switch to previous view
  
  # Action shortcuts
  actions:
    select: ["enter", " "]        # Select item or confirm
    cancel: ["esc"]               # Cancel operation
    toggle: ["space"]             # Toggle selection/state
    
    # Viewport navigation
    page_up: ["page_up", "ctrl+u"]
    page_down: ["page_down", "ctrl+d"]
    scroll_top: ["g"]
    scroll_bottom: ["G"]

# Component Configuration
components:
  # Workflow list component
  workflow_list:
    show_status_icons: true       # Show status symbols next to items
    show_progress: true           # Show progress bars for running workflows
    auto_scroll: true             # Auto-scroll to new items
    max_items: 100                # Maximum items to display
    filter_enabled: true          # Enable filtering/search
  
  # Tool execution table
  tool_table:
    show_recent_only: true        # Only show recent executions
    recent_limit: 50              # Number of recent items to keep
    show_duration: true           # Display execution duration
    show_args: false              # Hide command arguments by default
    auto_resize_columns: true     # Automatically adjust column widths
  
  # Log viewport
  log_viewport:
    max_entries: 1000             # Maximum log entries to keep
    auto_scroll: true             # Auto-scroll to new entries
    show_timestamps: true         # Show timestamp prefix
    show_levels: true             # Show log level indicators
    wrap_lines: true              # Wrap long lines
  
  # Progress indicators
  progress:
    show_percentage: true         # Show percentage next to bars
    animate_spinner: true         # Animate loading spinners
    update_frequency: 100         # Update frequency in milliseconds
  
  # Help panel
  help:
    show_all_shortcuts: false     # Show only relevant shortcuts by default
    markdown_rendering: true      # Use Glamour for markdown help
    auto_hide_timeout: 10         # Hide help after 10 seconds of inactivity

# Performance and Resource Configuration
performance:
  # Update frequencies (in milliseconds)
  update_intervals:
    ui_refresh: 100               # General UI refresh rate
    progress_update: 50           # Progress bar updates
    spinner_animation: 80         # Spinner animation speed
    log_refresh: 200              # Log viewport refresh
    system_stats: 1000            # System statistics update
  
  # Memory and resource limits
  limits:
    max_log_buffer: 1000          # Maximum log entries in memory
    max_tool_history: 100         # Maximum tool execution history
    max_notification_queue: 10    # Maximum pending notifications
    
  # Responsiveness settings
  responsiveness:
    resize_debounce: 100          # Debounce resize events (ms)
    input_debounce: 50            # Debounce key inputs (ms)
    async_rendering: true         # Use asynchronous rendering

# Development and Debug Configuration
debug:
  enabled: false                  # Enable debug mode
  show_render_time: false         # Show render time in debug mode
  log_messages: false             # Log all tea messages
  show_component_bounds: false    # Highlight component boundaries
  mock_data: false                # Use mock data for development

# Terminal Compatibility
terminal:
  # Fallback behavior for non-TTY environments
  non_tty:
    enabled: true                 # Enable non-TTY fallback
    use_color: false              # Disable colors in non-TTY mode
    show_progress: false          # Disable progress indicators
    compact_output: true          # Use compact text output
    
  # Terminal capability detection
  capabilities:
    detect_color_support: true    # Auto-detect color capabilities
    detect_unicode_support: true  # Auto-detect Unicode support
    fallback_to_ascii: true       # Use ASCII fallbacks when needed
    
  # Size constraints
  constraints:
    minimum_width: 40             # Absolute minimum terminal width
    minimum_height: 10            # Absolute minimum terminal height
    prefer_wide_layout: true      # Prefer horizontal layouts when possible