# IPCrawler TUI Configuration
ui:
  # Layout settings
  layout:
    breakpoints:
      small: 80    # Switch to stacked layout
      medium: 120  # Switch to three-column
    
    # Panel sizing (percentages)
    panels:
      list:
        width_large: 0.25   # 25% in large layout
        width_medium: 0.30  # 30% in medium layout
      main:
        width_large: 0.55   # 55% in large layout  
        width_medium: 0.70  # 70% in medium layout
      status:
        width_large: 0.20   # 20% in large layout
        height_footer: 4    # Footer height in medium/small
  
  # Theme configuration
  theme:
    # Color palette
    colors:
      primary: "#FAFAFA"
      secondary: "#3C3C3C" 
      accent: "86"          # Bright cyan for focused elements
      success: "#04B575"
      warning: "#F59E0B"
      error: "#EF4444"
      border: "240"         # Gray for unfocused borders
      focused: "86"         # Cyan for focused borders
      
    # Adaptive colors for light/dark terminals
    adaptive:
      text_primary:
        light: "236"
        dark: "248"
      border:
        light: "240" 
        dark: "238"
        
  # Component settings
  components:
    list:
      title: "Workflows & Tools"
      show_status_bar: false
      filtering_enabled: false    # Disabled due to key conflicts
      item_height: 3
      max_visible: 20             # Max items visible in list
      
    viewport:
      high_performance: true
      auto_scroll: true
      line_numbers: false
      scroll_speed: 3             # Lines to scroll per key press
      page_size: 10               # Lines for page up/down
      
    status:
      spinner: "dot"
      show_stats: true
      update_interval: 100ms
      
  # Keyboard bindings
  keys:
    quit: ["q", "ctrl+c"]
    tab: ["tab"]
    focus_list: ["1"]
    focus_main: ["2"] 
    focus_status: ["3"]
    
    # List navigation
    list_up: ["k", "up"]
    list_down: ["j", "down"]
    list_select: ["enter", "space"]
    list_filter: ["/"]
    
    # Viewport navigation  
    viewport_up: ["k", "up"]
    viewport_down: ["j", "down"]
    viewport_page_up: ["ctrl+b", "page_up"]
    viewport_page_down: ["ctrl+f", "page_down"]
    viewport_home: ["g"]
    viewport_end: ["G"]
    
  # Performance settings
  performance:
    alt_screen: true
    framerate_cap: 60
    batch_updates: true
    lazy_rendering: true
    max_concurrent: 5        # Max concurrent workflow executions
    buffer_size: 1000        # Output buffer size in lines
    
  # Display settings
  display:
    show_timestamps: true    # Show timestamps in logs
    show_progress: true      # Show progress bars
    show_spinner: true       # Show activity spinner
    word_wrap: true          # Word wrap long lines
    syntax_highlight: true   # Syntax highlighting for code
    
  # Workflow settings
  workflow:
    auto_queue: false        # Auto-add to queue on selection
    confirm_execute: true    # Confirm before execution
    stop_on_error: false     # Stop workflow on first error
    parallel_tools: 3        # Max parallel tool executions

