name: "Deep Service Analysis"
description: "Detailed service and version detection on discovered open ports"
parallel_group: "analysis"
requires:
  - "port-discovery"
steps:
  - tool: "nmap"
    args_sudo:
      - "-sS"              # Stealth SYN scan (requires root)
      - "-sV"              # Version detection
      - "--script=version"  # Only version detection scripts
      - "-O"               # OS detection (requires root)
      - "-Pn"              # Treat all hosts as online
      - "-T4"              # Aggressive timing (faster with sudo)
      - "-p"               # Port specification
      - "{{discovered_ports}}"  # Ports from port-discovery workflow
      - "-oX"              # XML output for JSON conversion
      - "nmap_deep_scan_{{target}}.xml"
      - "--max-retries=2"  # Limit retries to prevent hangs
      - "--host-timeout=300s"  # 5 minute timeout per host
      - "{{target}}"       # Target to scan
    args_normal:
      - "-sT"              # TCP connect scan (no root required)
      - "-sV"              # Version detection
      - "--script=version"  # Only version detection scripts
      - "-Pn"              # Treat all hosts as online
      - "-T3"              # Normal timing (more reliable for deep scan)
      - "-p"               # Port specification
      - "{{discovered_ports}}"  # Ports from port-discovery workflow
      - "-oX"              # XML output for JSON conversion
      - "nmap_deep_scan_{{target}}.xml"
      - "--max-retries=2"  # Limit retries to prevent hangs
      - "--host-timeout=300s"  # 5 minute timeout per host
      - "{{target}}"       # Target to scan